// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML2.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Chat {
	/**
	 * 
	 */
	public StanzaVirtuale[] listaStanze;
	/**
	 * 
	 */
	public Utente[] listaUtenti;

	/**
	 * 
	 * @param nomeStanza 
	 */
	public void creaStanza(String nomeStanza) {
	}

	/**
	 * 
	 * @param nomeStanza 
	 */
	public void eliminaStanza(String nomeStanza) {
	}

	/**
	 * 
	 */
	public void inviaAvviso() {
	}

	/**
	 * 
	 */
	public void aggiungiPartecipante() {
	}

	/**
	 * 
	 */
	public void rimuoviPartecipante() {
	}
}
