// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML2.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Messaggio {
	/**
	 * 
	 */
	public String data;
	/**
	 * 
	 */
	public String orario;
	/**
	 * 
	 */
	public String messaggio;
	/**
	 * 
	 */
	public Utente mittente;
	/**
	 * 
	 */
	public Utente destinatario;
	/**
	 * 
	 */
	public boolean pubblico;
}
