// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML2.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Moderatore extends Utente {
	/**
	 * 
	 */
	public Chat chat;
}
