// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML2.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class StanzaVirtuale {
	/**
	 * 
	 */
	public Utente[] partecipantiStanza;
	/**
	 * 
	 */
	public String nome;
	/**
	 * 
	 */
	public Messaggio[] messaggiPrivati;
	/**
	 * 
	 */
	public Messaggio[] messaggiPubblici;

	/**
	 * 
	 * @return 
	 */
	public Utente[] getPartecipanti() {
	}

	/**
	 * 
	 * @param messaggio 
	 * @param utente 
	 */
	public void inviaMessaggioPrivato(Messaggio messaggio, String utente) {
	}

	/**
	 * 
	 * @param messaggio 
	 */
	public void inviaMessaggioPubblico(Messaggio messaggio) {
	}
}
