// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML2.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Utente {
	/**
	 * 
	 */
	public String username;
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public StanzaVirtuale[] stanze;
}
