// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML1.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Corso {
	/**
	 * 
	 */
	public Task[] task;
	/**
	 * 
	 */
	public String nome;
	/**
	 * 
	 */
	public boolean primoSemestre;

	/**
	 * 
	 */
	public void delAmministratore() {
	}

	/**
	 * 
	 */
	public void addAmministratore() {
	}

	/**
	 * 
	 */
	public void getTask() {
	}

	/**
	 * 
	 */
	public void getStudenti() {
	}

	/**
	 * 
	 */
	public void creaTask() {
	}

	/**
	 * 
	 */
	public void caricaDocumento() {
	}

	/**
	 * 
	 */
	public void informaProfessore() {
	}

	/**
	 * 
	 */
	public void informaStudente() {
	}

	/**
	 * 
	 */
	public void rilasciaCertificato() {
	}
}
