// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML1.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Professore extends Utente {
	/**
	 * 
	 */
	public Corso[] corsi;
	/**
	 * 
	 */
	public String dipartimento;
	/**
	 * 
	 */
	public Corso[] corsiAdmin;
	/**
	 * 
	 */
	public Sottomissione[] sottomissioniAssegnate;

	/**
	 * 
	 */
	public void getCorsi() {
	}

	/**
	 * 
	 */
	public void getCorsiAdmin() {
	}
}
