// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML1.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Sottomissione {
	/**
	 * 
	 */
	public Task task;
	/**
	 * 
	 */
	public String documentoPath;
	/**
	 * 
	 */
	public EDate data;
	/**
	 * 
	 */
	public int punteggio;

	/**
	 * 
	 * @param nome 
	 */
	public void assegnaProfessore(String nome) {
	}

	/**
	 * 
	 */
	public void caricaDocumento() {
	}

	/**
	 * 
	 * @param punteggio 
	 */
	public void setPunteggio(int punteggio) {
	}
}
