// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML1.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Studente extends Utente {
	/**
	 * 
	 */
	public String matricola;

	/**
	 * 
	 */
	public void infoCertificati() {
	}
}
