// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML1.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Task {
	/**
	 * 
	 */
	public String descrizione;
	/**
	 * 
	 */
	public int maxPunti;
	/**
	 * 
	 */
	public EDate deadline;

	/**
	 * 
	 */
	public void updateDati() {
	}

	/**
	 * 
	 */
	public void getDati() {
	}

	/**
	 * 
	 * @return 
	 */
	public Sottomissione getSottomissioni() {
	}
}
