// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML1.ClassDiagram;

/************************************************************/
/**
 * 
 */
public enum TipoAut {
	/**
	 * 
	 */
	ADMIN,
	/**
	 * 
	 */
	STANDARD;
}
