// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EsercitazioneUML1.ClassDiagram;

/************************************************************/
/**
 * 
 */
public class Utente {
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public String username;
	/**
	 * 
	 */
	public String nome;
	/**
	 * 
	 */
	public TipoAut tipoAut;

	/**
	 * 
	 */
	public void getDati() {
	}

	/**
	 * 
	 */
	public void setDati() {
	}

	/**
	 * 
	 */
	public void notifica() {
	}
}
